// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	DeletePost(ctx context.Context, id int32) error
	GetPostById(ctx context.Context, id int32) (Post, error)
	GetPosts(ctx context.Context) ([]Post, error)
	UpdatePostById(ctx context.Context, arg UpdatePostByIdParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
